version: '3.8'
services:
  modulbank:
    build:
      context: .
      dockerfile: ./AccountService/Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Production
      - Authentication__Audience=account-service
      - Authentication__Issuer=http://localhost:8080/realms/modulbank
      - Authentication__MetadataAddress=http://keycloak:8080/realms/modulbank/.well-known/openid-configuration
      - Authentication__RequireHttpsMetadata=false
      - Database__ConnectionStrings=Host=db;Port=5432;Database=modulbankdb;Username=modulbankuser;Password=modulbankpass
      - Database__MustMigrate=true

    depends_on:
      - db
      - keycloak
    networks:
      - keycloak-network

  db:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=modulbankuser
      - POSTGRES_PASSWORD=modulbankpass
      - POSTGRES_DB=modulbankdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
    networks:
      - keycloak-network

volumes:
  db_data:

networks:
  keycloak-network:
    driver: bridge
